### ISSUE TITLE
Add OAuth 2.0 support

### ISSUE THREAD

**Issue by drone-rites** [drone-rites/clj-oauth#28]
Add support for OAuth 2.0 to work with Google's APIs:
https://developers.google.com/accounts/docs/OAuth2UserAgent

**Comment by sdmoralesma** [comment]
Are there any plans on this or do you recommend to use another lib?

**Comment by mattrepl** [comment]
Sorry for the slow response. I'm glad to accept PRs to add OAuth 2.0 support, but I don't have the time to write it myself. There are likely other libraries that support OAuth 2.0.
