### ISSUE TITLE
Trouble Related to Signature Creation with OAuth and Odesk API

### ISSUE THREAD

**Issue by artstwolf** [drone-rites/clj-oauth#36]
Hello,

I've been using this library in order to interact with the ODesk API (http://developers.odesk.com/w/page/12364003/FrontPage), and it has been very helpful. Thank you!  However, I did have some trouble with some post requests to match the signature created with OAuth.  One of the major problems I encountered was with spaces in the parameter values:

``` clojure
(def params {:recipients "my_recipient"
            :subject "Spaces Cause Problems"
            :body "Spaces in text cause strange signature mismatches."})
(def credentials (oauth/credentials consumer
                          (:oauth_token access-token-response)
                          (:oauth_token_secret access-token-response)
                          :POST
                          "https://www.odesk.com/api/mc/v1/threads/my_username.json"
                          params))
;using clj-http
(http/post "https://www.odesk.com/api/mc/v1/threads/my_username.json"
           {:form-params (merge params credentials)})
```

This post returns a signature mismatch error (401).  After some sleuthing, it seemed that the form encoding was slightly different for the OAuth than http/post such that replacing spaces with pluses before creating the signature fixes the problem.

``` clojure
(defn encode-params [params]
    (into {} (map #(vector (first %) (.replace (second %) " " "+")) params)))
;;eg. {:key "Hello World"} becomes {:key "Hello+World"}
```

Using "encoded" parameters before creating the signature and then using the original "unencoded" parameters for the http POST generates a successful request:

``` clojure
(def params {:recipients "my_recipient"
            :subject "Spaces Cause Problems"
            :body "Spaces in text cause strange signature mismatches."})
(def credentials (oauth/credentials consumer
                          (:oauth_token access-token-response)
                          (:oauth_token_secret access-token-response)
                          :POST
                          "https://www.odesk.com/api/mc/v1/threads/my_username.json"
                          (encode-params params)))
;using clj-http
(http/post "https://www.odesk.com/api/mc/v1/threads/my_username.json"
           {:form-params (merge params credentials)})
```

In the case above, encode-params translates "Spaces Cause Problems" into "Spaces+Cause+Problems" for signature creation, but leaves it as "Spaces Cause Problems" for the http/post.  This work around was successful.

It is very possible that there is an easier way to send a post request with parameters that contain spaces that I am missing.  Did I miss something or is this translation necessary?

Thank you in advance for your input!

**Comment by drone29a** [comment]
Closing, appears to be issue with ODesk's implementation.
